### ISSUE TITLE
TypeError: this.buffers[pos.buf].get is not a function

### ISSUE THREAD

**Issue by 64jcl** [TooTallNate/node-telnet#20]
Running the simple example and connecting to it with e.g. Putty kills the server with the following error after it has returned some data:

.. node_modules\telnet\node_modules\buffers\index.js:185
    return this.buffers[pos.buf].get(pos.offset);

TypeError: this.buffers[pos.buf].get is not a function
    at Buffers.get (C:\Users\jcl\AppData\Roaming\npm\node_modules\telnet\node_modules\buffers\index.js:185:34)
    at parse (C:\Users\jcl\AppData\Roaming\npm\node_modules\telnet\lib\telnet.js:145:15)
    at Socket.<anonymous> (C:\Users\jcl\AppData\Roaming\npm\node_modules\telnet\lib\telnet.js:201:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by 64jcl** [comment]
Ok I found the solution to the problem here:

https://github.com/substack/node-buffers/issues/16

**Comment by cscott** [comment]
The version on the master branch here fixes that problem.  Unfortunately, @TooTallNate never actually released it to npm.  You can make this change to your package.json as a workaround:
```
-    "telnet": "0.0.1"
+    "telnet": "git+https://github.com/TooTallNate/node-telnet.git#780340617e1f223de384cdfcb7cecf0a1a6f1159"
```
